version: '3'
services:
    node:
        container_name: node_preguntas2
        image: "euechi/orbis-training-docker:4.2.0"
        ports:
            - "1024:3030"
        command: npm start
        working_dir: /app